name: Run Python Script at 2:03 PM PST

on:
  schedule:
    - cron: '10 22 * * *' # Adjusted for UTC time (2:03 PM PST = 10:03 PM UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Replace 'x' with the desired Python version


      - name: Run Python Script
        run: python C:\Users\DELGAVI\Desktop\Stuff\python\learn_github\test.py # Replace with the actual path to your Python script
