name: fart workflow

on:
  schedule:
    - cron: '36 j j 16 * * *' 

  # workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "farts"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: end test
        run: echo "poops"
        shell: bash
